name: Build and Test

on: [push]

jobs:
  build_and_test:

    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Select xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app && /usr/bin/xcodebuild -version

      - name: Build and test 
        run: xcodebuild test -project ios/voicebox.xcodeproj -scheme voicebox -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (5th generation),OS=16.0' 
